# Generated by Django 4.2.26 on 2025-11-10 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('code_hash', models.CharField(max_length=64, unique=True, verbose_name='코드 해시')),
                ('output', models.TextField(verbose_name='출력 결과')),
                ('execution_time', models.FloatField(verbose_name='실행 시간(초)')),
                ('hit_count', models.IntegerField(default=0, verbose_name='캐시 히트 횟수')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '실행 결과 캐시',
                'verbose_name_plural': '실행 결과 캐시',
                'ordering': ['-hit_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('code', models.TextField(verbose_name='실행 코드')),
                ('execution_mode', models.CharField(default='restricted', max_length=20, verbose_name='실행 모드')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('running', '실행중'), ('success', '성공'), ('error', '오류'), ('timeout', '타임아웃')], default='pending', max_length=20, verbose_name='상태')),
                ('output', models.TextField(blank=True, null=True, verbose_name='출력 결과')),
                ('error', models.TextField(blank=True, null=True, verbose_name='에러 메시지')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='실행 시간(초)')),
                ('memory_used', models.IntegerField(blank=True, null=True, verbose_name='메모리 사용량(MB)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '실행 로그',
                'verbose_name_plural': '실행 로그',
                'ordering': ['-created_at'],
            },
        ),
    ]
