# Generated by Django 4.2.26 on 2025-11-10 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='카테고리명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '템플릿 카테고리',
                'verbose_name_plural': '템플릿 카테고리',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('name', models.CharField(max_length=200, verbose_name='템플릿명')),
                ('category_type', models.CharField(choices=[('grid', '그리드 조회'), ('chart', '차트 조회'), ('regression', '회귀분석'), ('classification', '분류분석'), ('clustering', '클러스터링'), ('data_processing', '데이터 처리'), ('other', '기타')], default='other', max_length=50, verbose_name='카테고리 타입')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('code', models.TextField(verbose_name='템플릿 코드')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개')),
                ('usage_count', models.IntegerField(default=0, verbose_name='사용 횟수')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='태그')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates.templatecategory', verbose_name='카테고리')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '템플릿',
                'verbose_name_plural': '템플릿',
                'ordering': ['category_type', 'name'],
            },
        ),
    ]
